### ISSUE TITLE
Conocer/evaluar los requerimientos de uso

### ISSUE THREAD

**Issue by JonRecarte** [JonRecarte/ReactNativeLesson#23]

**Comment by YoucefKaced77** [comment]
**TASK REVIEW:**

**Sistema de planificación de tareas llevada a cabo:**

- milestone por cada nueva funcionalidad definida en los requerimientos del proyecto.

- Crear tantos issues como sean necesarios por cada milestone, de manera que asocias todos los issues al milestone al que pertenece el ejercicio - En este "Decidir que 5 capacidades nativas se van a implementar #25"

- Asociar una etiqueta "Doing" al issue que se esté realizando en ese momento y una "Done/Backlog" cuando se cierre un issue

**Tareas realizadas:**

- Lo primero de todo ha sido evaluar el escenario en el que nos encontrábamos, analizar las variables con las que jugábamos, tomar las mejores decisiones en base a ello e ir a por todas hasta el final.
