### ISSUE TITLE
Decidir que 5 capacidades nativas se van a implementar

### ISSUE THREAD

**Issue by JonRecarte** [JonRecarte/ReactNativeLesson#25]

**Comment by YoucefKaced77** [comment]
**TASK REVIEW:**

**Sistema de planificación de tareas llevada a cabo:**

- milestone por cada nueva funcionalidad definida en los requerimientos del proyecto.

- Crear tantos issues como sean necesarios por cada milestone, de manera que asocias todos los issues al milestone al que pertenece el ejercicio - En este "Decidir que 5 capacidades nativas se van a implementar #25"

- Asociar una etiqueta "Doing" al issue que se esté realizando en ese momento y una "Done/Backlog" cuando se cierre un issue

**Tareas realizadas:**

- Se ha decidido emplear las siguientes 5 capacidades nativas. Ha sido ciertamente complicado, porque sí que es verdad que había una amplia gama de posibilidades, pero a pocas se les podía dar una funcionalidad integrada en nuestro proyecto. Las elegidas han sido: Google Maps, Ubicación, Cámara, Galería y Correo Electrónico.


**Diferencia entre lo esperado y lo ocurrido:**

- La realidad es que al principio elegimos unas, luego una vez hechas ya no nos gustaban tanto, así que tuvimos que pivotar. Asía unas cuantas veces.

**Retos fuera de la práctica y opinión personal:**

- Ha servido para darse cuenta de la cantidad o amplia gama de funcionalidades que se pueden implementar de una manera bastante rápida.
